---
  - name: clone Destalinator source
    git:
      repo: https://github.com/randsleadershipslack/destalinator.git
      dest: "{{ destalinator_dir }}"

  - name: build Destalinator Docker image
    docker_image:
      path: "{{ destalinator_dir }}"
      name: destalinator

  - name: run Destalinator Docker container
    docker_container:
      name: Destalinator
      image: destalinator
      restart_policy: always
      env:
        # DESTALINATOR_RUN_ONCE: "true"
        DESTALINATOR_ACTIVATED: "true"
        DESTALINATOR_SB_TOKEN: "{{ d_sb_token }}"
        DESTALINATOR_API_TOKEN: "{{ d_api_token }}"
        DESTALINATOR_LOG_LEVEL: "{{ d_log_level }}"
        DESTALINATOR_LOG_TO_CHANNEL: "{{ d_log_to_channel }}"
        DESTALINATOR_SLACK_NAME: "{{ d_slack_name }}"
        DESTALINATOR_BOT_NAME: "{{ d_bot_name }}"
        DESTALINATOR_BOT_AVATAR_URL: "{{ d_bot_avatar_url }}"
        DESTALINATOR_WARN_THRESHOLD: "{{ d_warn_threshold }}"
        DESTALINATOR_ARCHIVE_THRESHOLD: "{{ d_archive_threshold }}"
        DESTALINATOR_GENERAL_MESSAGE_CHANNEL: "{{ d_general_message_channel }}"
        DESTALINATOR_ANNOUNCE_CHANNEL: "{{ d_announce_channel }}"
        DESTALINATOR_CONTROL_CHANNEL: "{{ d_control_channel }}"
        DESTALINATOR_LOG_CHANNEL: "{{ d_log_channel }}"
        DESTALINATOR_IGNORE_CHANNELS: "{{ d_ignore_channels }}"
        DESTALINATOR_IGNORE_CHANNEL_PATTERNS: "{{ d_ignore_channel_patterns }}"
        DESTALINATOR_IGNORE_USERS: "{{ d_ignore_users }}"
        DESTALINATOR_INCLUDED_SUBTYPES: "{{ d_included_subtypes }}"
        DESTALINATOR_SCHEDULE_HOUR: "{{ d_schedule_hour }}"
