---
  - name: update apt errday
    cron:
      name: update
      minute: 0
      hour: 0
      job: /usr/bin/apt-get update

  - name: update all packages errday
    cron:
      name: upgrade
      minute: 15
      hour: 0
      job: /usr/bin/apt-get -y dist-upgrade

  - name: remove dead deps errday
    cron:
      name: autoremove
      minute: 30
      hour: 0
      job: /usr/bin/apt-get -y autoremove
