---
  - name: install Docker prereqs
    apt:
      name: "{{ item }}"
      update_cache: yes
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

  - name: install Docker apt key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

  - name: register Docker apt repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu xenial stable

  - name: install Docker
    apt:
      name: "{{ item }}"
      update_cache: yes
    with_items:
      - docker-ce
      - python-docker
